[tool.poetry]
name = "pytest_bdd_example"
version = "0.1.0"
description = "An example of pytest-bdd test"
authors = ["chatgpt lol"]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.2.0"
pytest-bdd = "^6.1.1"

[tool.poetry.dev-dependencies]